//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int id { get; set; }
        public int appointment_id { get; set; }
        public int drug_id { get; set; }
        public Nullable<int> quantity_sold { get; set; }
        public Nullable<int> price_sold { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Appointment Appointment { get; set; }
    }
}
